# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

# Runs on pushes targeting the default branch
on:
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages:    write # to deploy to Pages
  id-token: write # to verify the deployment originates from an appropriate source

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# See actions/starter-workflows repo for details.
# https://github.com/actions/starter-workflows/blob/main/pages/static.yml
#
# Single deploy job since we're just deploying
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      # This is NOT for security reason but for others, especially who fork,
      # to easier find out which API key they need to replace with their own.
      # Check out the official tutorial for details: https://docs.geolonia.com/tutorial
      - name: "Replace Geolonia's YOUR-API-KEY with secrets"
        env:
          GEOLONIA_API_KEY: ${{ secrets.GEOLONIA_API_KEY }}
        run: |
          ruby -i -pe '$_.gsub!("geolonia-api-key=YOUR-API-KEY",
                                "geolonia-api-key=${{ env.GEOLONIA_API_KEY }}")' index.html

      - name: "Setup Pages"
        uses: actions/configure-pages@v2
      - name: "Upload artifact"
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: "Deploy to GitHub Pages"
        id:   deployment
        uses: actions/deploy-pages@v1
